# Generated by Django 3.1 on 2020-09-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200903_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='picture',
        ),
    ]
