# Generated by Django 3.1 on 2020-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20200906_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profiles/default/default_profile_image.jpg', null=True, upload_to='profiles/images/%Y/%m/%d'),
        ),
    ]
