# Generated by Django 3.1 on 2020-10-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_auto_20200909_1114'),
        ('user_management', '0006_auto_20200909_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.CreateModel(
            name='ProfileBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('READING', 'In lettura'), ('READ', 'Letto'), ('MUSTREAD', 'Da leggere')], default='READ', max_length=8)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='book_management.book')),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='user_management.profile')),
            ],
            options={
                'unique_together': {('profile_owner', 'book')},
            },
        ),
    ]
