# Generated by Django 3.1 on 2020-10-22 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0003_auto_20200909_1114'),
        ('user_management', '0007_auto_20201020_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilebook',
            old_name='status',
            new_name='_status',
        ),
        migrations.AlterField(
            model_name='profilebook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_books', to='book_management.book'),
        ),
    ]
