# Generated by Django 3.1 on 2020-10-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20201022_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebook',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=-1, max_length=3, null=True),
        ),
    ]
