# Generated by Django 3.1 on 2020-10-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_profilebook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebook',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=-1, null=True),
        ),
    ]
