# Generated by Django 3.1 on 2020-10-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_auto_20201026_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilebook',
            options={'ordering': ['-creation_date_time']},
        ),
    ]
