# Generated by Django 3.1 on 2020-10-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0012_auto_20201027_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starting_follow_date_time',
            field=models.IntegerField(default=1),
        ),
    ]
