# Generated by Django 3.1 on 2020-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_profile_starting_follow_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='starting_follow_date_time',
            field=models.DateTimeField(),
        ),
    ]
