# Generated by Django 3.1 on 2020-10-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_auto_20201028_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starting_follow_date_time',
        ),
    ]
