# Generated by Django 3.1 on 2020-10-28 17:24
import datetime

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Profile = apps.get_model('user_management', 'Profile')
    Follower = apps.get_model('user_management', 'Follower')
    for profile in Profile.objects.all():
        for follower in profile.followers.all():
            Follower(
                user_following=follower,
                profile_followed=profile,
                starting_follow_date_time=datetime.date.today()
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0016_follower'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop)
    ]
