# Generated by Django 3.1 on 2020-10-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_auto_20201028_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
