# Generated by Django 3.1 on 2020-10-28 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0018_remove_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followed_profiles', through='user_management.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
