# Generated by Django 3.1 on 2020-10-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0019_profile_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_follow_date_time', models.DateTimeField(auto_now_add=True)),
                ('profile_followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to='user_management.profile')),
                ('user_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followed_profiles', through='user_management.FollowRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
