# Generated by Django 3.1 on 2020-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_auto_20201028_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrelation',
            name='a',
            field=models.IntegerField(default=10),
        ),
    ]
