# Generated by Django 3.1 on 2020-10-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_followrelation_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrelation',
            name='a',
        ),
    ]
