# Generated by Django 3.1 on 2020-10-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0022_remove_followrelation_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebook',
            name='end_reading_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilebook',
            name='start_reading_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
