# Generated by Django 3.1 on 2020-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_auto_20201030_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebook',
            name='end_reading_date_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilebook',
            name='start_reading_date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
