# Generated by Django 3.1 on 2020-10-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_auto_20201030_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilebook',
            old_name='end_reading_date_time',
            new_name='end_reading_date',
        ),
        migrations.RenameField(
            model_name='profilebook',
            old_name='start_reading_date_time',
            new_name='start_reading_date',
        ),
    ]
