# Generated by Django 3.1 on 2020-10-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0025_auto_20201030_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebook',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
