# Generated by Django 3.1 on 2020-10-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_auto_20201030_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebook',
            name='rating',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
