# Generated by Django 3.1 on 2020-10-30 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_auto_20201030_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebook',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
