# Generated by Django 3.1 on 2020-10-31 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0028_auto_20201030_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformuser',
            name='terms_of_service_acceptance',
        ),
        migrations.RemoveField(
            model_name='platformuser',
            name='terms_of_service_acceptance_datetime',
        ),
    ]
