# Generated by Django 3.1 on 2020-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0029_auto_20201031_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilebook',
            options={'ordering': ['-last_update_date_time']},
        ),
        migrations.AddField(
            model_name='profilebook',
            name='last_update_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
