# Generated by Django 3.1 on 2020-09-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
                ('cover_image_file', models.ImageField(default='static/database_files/default_book_cover_image.png', upload_to='static/database_files')),
                ('cover_image_url', models.URLField(blank=True, null=True)),
                ('isbn_10', models.CharField(max_length=20)),
                ('isbn_13', models.CharField(max_length=20)),
                ('average_reviews', models.PositiveSmallIntegerField(default=0)),
                ('authors', models.ManyToManyField(related_name='book_authors', to='book_management.Author')),
            ],
        ),
    ]
