# Generated by Django 3.1 on 2020-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_auto_20200903_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='average_reviews',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_file',
            field=models.ImageField(default='books_cover/default/default_cover.png', upload_to='books_cover/'),
        ),
    ]
