# Generated by Django 3.1 on 2020-10-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
    ]
