# Generated by Django 3.1 on 2020-10-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_management', '0002_auto_20201028_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-pk']},
        ),
    ]
